### ISSUE TITLE
the mod is not working

### ISSUE THREAD

**Issue by hanfei831** [c0dycode/BL3HotfixWebUI#11]
My game runs as usual but the mod is not working.
And i am convinced the vcredists installed.
And it shows 0\1568 in the games.
logs from webUI
`2021-7-18 17:27:28 : [Info] Same amount of hotfixes detected after merging.
2021-7-18 17:27:28 : Failed to get custom hotfixes: Get "https://raw.githubusercontent.com/BLCM/bl3mods/master/Stygian%20Emperor/Moze/IronBearUnlimitedFuel/StygianEmperor_IronBearUnlimitedFuel_FullRefund.bl3hotfix": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.
2021-7-18 17:26:23 : Injected DLL into Borderlands3.exe
2021-7-18 17:26:03 : Succesfully patched StartupMovies
2021-7-18 17:26:03 : Borderlands 3 process found!
2021-7-18 17:25:55 : Waiting for Borderlands3.exe...
2021-7-18 17:23:13 : Failed to write port to injected dll: dll was not injected
2021-7-18 17:22:19 : Failed to patch StartupMovies: pattern not found
2021-7-18 17:22:14 : Borderlands 3 process found!
2021-7-18 17:21:07 : Waiting for Borderlands3.exe...
2021-7-18 17:21:07 : Starting ProxyServer! `

**Comment by c0dycode** [comment]
I believe that this is the same issue that I already fixed for version 1.02 (not released yet).
It has something to do with the "%20" which is not correctly handled prior to 1.02.

For now, the easiest workaround is to download that mod to your local pc and add that via the "Add Local Path" option in the webui.

**Comment by hanfei831** [comment]
It works.thx.And when will the 1.02 be released?

**Comment by c0dycode** [comment]
No eta yet, unfortunately.
I currently do not have that much time available, so it might take a while. :/
