### ISSUE TITLE
DX12 support in the DLL

### ISSUE THREAD

**Issue by slippycheeze** [c0dycode/BL3HotfixWebUI#15]
It'd be quite nice to be able to play with the DX12 renderer; right now, if I switch to that I get a NULL pointer deref from the BL3 process during startup, for some reason.  Running DX11 works fine.   This is the epic store version, so IDK if that might be why, but far as I can tell it isn't.

**Comment by c0dycode** [comment]
This is most likely related to the "Plugin Loader".
https://github.com/FromDarkHell/BL3DX11Injection

Make sure you got the most recent version of that.

Apart from that, B3HM itself doesn't mess with anything DirectX-related, but the game randomly does this for me on DX12 too - even without B3HM and the PluginLoader.

So I'm fairly certain that some of those are actually a game issue.

**Comment by slippycheeze** [comment]
I'm currently using the "executable" injector; beyond that, I'll see if I can figure out what is going on more.  Thank you for clarifying that.
