### ISSUE TITLE
 the game stays on the login screen without advancing but without freezing

### ISSUE THREAD

**Issue by LILLK** [c0dycode/BL3HotfixWebUI#18]
I am with a pirated version of bd3 to be able to play the dlc where the hotfix previously worked for me but when I reinstall the game because I had to delete it, the game stays on the login screen without advancing but without freezing

**Comment by FromDarkHell** [comment]
We cannot/will not actively provide support for pirated/cracked copies of the game.

**Comment by LILLK** [comment]
understandable
