### ISSUE TITLE
Presets fail to load -The system cannot find the file specified-

### ISSUE THREAD

**Issue by MillionLights** [c0dycode/BL3HotfixWebUI#4]
Presets fail to load

Probably due to spaces in directory name?

2020-12-25 07:33:07 : Failed to read preset-file: open G:\Steam Games\steamapps\common\Borderlands 3\OakGame\Binaries\Win64\Presets\myMods.prst: The system cannot find the file specified.

I wont reinstall the game to somewhere else to confirm this but it's a common issue so I'm assuming thats the issue.

**Comment by c0dycode** [comment]
The directory name does not really matter.
Presets are loaded & saved relative to the current working directory of the process.
So for the DLL the working directory will be
`Borderlands 3\OakGame\Binaries\Win64`

and for the exe version, it's wherever the exe itself is located at.

I've just tested this with the DLL and even presets that have a space in the filename itself, as you can see here.
![image](https://user-images.githubusercontent.com/3851319/103132806-ca734700-46a6-11eb-8060-92c7801fcfcc.png)

Double check that the file actually exist. Maybe your antivirus is trying to be smart and silently removes the file(s)?

**Comment by MillionLights** [comment]
Interesting.
When I tried it this time everything worked again. I didnt even change anything.
Sorry about that report. If it happens again I'll investigate it further

**Comment by c0dycode** [comment]
No worries.
This might be an edge-case. So probably difficult to debug anyway.
If it DOES happen again, feel free to re-open and I'll try to investigate. :)
