### ISSUE TITLE
[WebUI] Limit the names of acceptable presets

### ISSUE THREAD

**Issue by FromDarkHell** [c0dycode/BL3HotfixWebUI#5]
See stuff like:
![image](https://user-images.githubusercontent.com/9018764/103187869-c48a8b00-488b-11eb-889e-08f623e4ec41.png)

**Comment by c0dycode** [comment]
I've added these
`'<', '>', ':', '"', '/', '\', '|', '?', '*', '^'` [from MS](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) to an invalid character-map and the log should print an error to the console if they're found and lets the user know which characters are invalid.

![image](https://user-images.githubusercontent.com/3851319/103215720-7a99b780-4914-11eb-889a-d607a73123d1.png)

That should be sufficient imo.
