### ISSUE TITLE
Steam failure to launch game

### ISSUE THREAD

**Issue by zithorol** [c0dycode/BL3HotfixWebUI#8]
Just tried to install on steam today. When i try to launch the game it tried to open then immediately closes. So i tried laumching fron the exe in the win64 folder and it says " The code execution cannot proceed because d3d11_org.dll was not found"(a file namedd3d11.dll is in the folder with the BL3 exe) . Reinstalling the program may fix this problem. not sure if this is because the recent update or just my missing something. though on install i followed the video step by step. thanks for any help you can provide
Windows 10 OS
i did install the vcredist(s) as well
also should note that the pluginloader does not open when the game fails to open

**Comment by c0dycode** [comment]
Wrong repo :P
This is the one for the PluginLoader: https://github.com/FromDarkHell/BL3DX11Injection
